<script setup lang="ts">
/**
 * SVG Symbols component - Generated by IconForge CLI
 * Include this component once at the root of your app (e.g., App.vue or layout)
 */
defineOptions({
  name: "SvgSymbols",
});
</script>

<template>
  <svg
    style="position: absolute; width: 0; height: 0; overflow: hidden"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <symbol id="close" viewBox="0 0 24 24">
      <path d="M18 6 6 18M6 6l12 12" fill="none" stroke="currentColor" />
    </symbol>
    <symbol id="home" viewBox="0 0 24 24">
      <path
        d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
        fill="none"
        stroke="currentColor"
      />
      <path d="M9 22V12h6v10" fill="none" stroke="currentColor" />
    </symbol>
    <symbol id="menu" viewBox="0 0 24 24">
      <path d="M3 12h18M3 6h18M3 18h18" fill="none" stroke="currentColor" />
    </symbol>
  </svg>
</template>
